# Generated by Django 5.0.4 on 2024-04-19 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='users.category'),
            preserve_default=False,
        ),
    ]
