# Generated by Django 5.0.4 on 2024-04-19 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_book_category_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='category_id',
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
