# Generated by Django 5.0.4 on 2024-04-19 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_book_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='total_price',
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(default='COD', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='price',
            field=models.OneToOneField(default=500, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='users.book'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='book_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='users.book'),
        ),
    ]
