# Generated by Django 5.0.4 on 2024-04-19 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_transaction_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('order received', 'Order Received'), ('sold', 'Sold')], default='available', max_length=20),
        ),
    ]
