# Generated by Django 5.0.4 on 2024-04-20 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_shippingaddress_transaction_shipping_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='shipping_address',
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='transaction',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.transaction'),
            preserve_default=False,
        ),
    ]
